CREATE TABLE IF NOT EXISTS teams (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  city VARCHAR(255) NOT NULL,
  conference VARCHAR(255) NOT NULL,
  championships INTEGER NOT NULL,
  win_rate FLOAT NOT NULL,
  is_champion BOOLEAN NOT NULL
);